### ISSUE TITLE
Enumerating event properties in Seq.App.Email doesn't seem to work

### ISSUE THREAD

**Issue by caioproiete** [datalust/seq-apps#22]
I'm running `Seq v3.3.23` with `Seq.App.Email v2.0.44` and followed the [instructions in the docs to display a list of properties and values](http://docs.getseq.net/docs/formatting-html-email#section-enumerating-event-properties) in the `Properties` bag and it doesn't get rendered in the e-mail.

```
<ul>
  {{#each $Properties}}
  <li>{{@key}} is {{pretty this}}</li>
  {{/each}}
</u>
```

I tried `{{$Properties}}`, `{{@Properties}}`, and `{{Properties}}` just to be sure, and none worked. The code above is displayed as is in the e-mail body, instead of it being rendered.

**Comment by nblumhardt** [comment]
Hi Caio, thanks for the note. I've tried this using the versions you mention and can't seem to reproduce any issue - the properties come through as expected.

Is it possible there's a syntax error earlier in the template that's upsetting things? (I am only testing the literal snippet above).

The default template, in case you want to paste it in and check out the results, is: https://github.com/datalust/seq-apps/blob/master/src/Seq.App.EmailPlus/Resources/DefaultBodyTemplate.html - does it render correctly for you?

**Comment by caioproiete** [comment]
Hey @nblumhardt. Sorry for the delay, we've got hit by a hurricane just after I opened the issue, and things are just getting back to normal.

I tested with the default template, and I'm still getting the same behavior. Screenshot below:

![image](https://cloud.githubusercontent.com/assets/177608/19447100/5d478848-9472-11e6-9ad3-5a530d0dcfa5.png)

This is how the Seq app config looks like (the HTML is a copy/paste of the DefaultBodyTemplate.html from above):

![image](https://cloud.githubusercontent.com/assets/177608/19447174/af35437a-9472-11e6-8b8f-f87c6038e767.png)

It seems that variables starting with **$** are never rendered, whereas variables starting with **@** are rendered (as you can see in the subject of the e-mail).

Any ideas?

**Comment by nblumhardt** [comment]
> we've got hit by a hurricane just after I opened the issue

Yikes! I hope you and your family all came through safely and without too much to clean up.

The subject template was the clue I needed:

![image](https://cloud.githubusercontent.com/assets/342712/19458043/ea4204ea-950c-11e6-84e5-225c4ae7879b.png)

To:

![image](https://cloud.githubusercontent.com/assets/342712/19458050/f5a33cb4-950c-11e6-8eb4-736c1d9fd1e2.png)

Unfortunately I missed that you specified _Seq.App.Email_, not _Seq.App.Email**Plus**_ - the docs etc. are all describing the new app. The old app is still published, so that existing installations can be maintained, but the new app is the one to use.

I will give some thought to how we can make this less of a trap - sorry about the confusion.

All works as expected with Seq.App.EmailPlus?

**Comment by nblumhardt** [comment]
Added note to the docs: http://docs.getseq.net/v3/docs/formatting-html-email

**Comment by caioproiete** [comment]
Ah! I knew it had to be something as simple as that. I guess I missed the change from Email to EmailPlus, which works as expected.

Thanks for your help.

ps: Yes, we all came through safely and zero casualties on the island. The weekend was enough to do all the major cleaning, so all good now, back to normal :) Thanks!
