### ISSUE TITLE
SeqApp in Seq v3

### ISSUE THREAD

**Issue by stevescc** [datalust/seq-apps#24]
Hi

I've had success in the past with Seq.Apps but I haven't been able to get my Seq Apps to work since updating to Seq v3 (the specific version I'm on is 3.3.23). To make my issue easily replicable, I cloned this repo, open sln, and replaced everything in the Seq.App.FileArchive On method with an internal log. Ie.
```
public void On(Event<LogEventData> evt)
{
      this.Log.Debug("log me");
}
```
I package it with nuget v3.4.4, install it and start an instance in my local Seq, then manually add an event, and after waiting a while I don't see any log.
Is this just something funny I'm experiencing/doing-wrong or is there an issue?

Thanks
Steve

**Comment by nblumhardt** [comment]
Hi Steve, thanks for getting in touch. Do you mean apps that you've written yourself, or the email/file archive/etc. apps published from here?

If it's the apps we ship, you may need to update them after upgrading (you can do this from _Apps_ > _Manage_).

Otherwise, if it's your own apps that are failing, you may need to upgrade them to a more recent Serilog version (if you're referencing it), e.g. 2.2.0.

In either case, there should be some diagnostic info in `C:\ProgramData\Seq\Logs`. Can you spot any clues in there?

All the best,
Nick

**Comment by stevescc** [comment]
Hi Nick,
This is referring to apps I've written myself, based off Seq.App.FileArchive. The ProgramData logs have given me clues thanks. First it said it couldn't find `Serilog.Sinks.RollingFile`, so I added it to the nuspec. Then it said `System.MissingMethodException: Method not found: 'Serilog.Core.Logger Serilog.LoggerConfiguration.CreateLogger()'`, so I added all the dlls in the release folder
```
    <file src="bin\Release\Serilog.dll" target="lib\net45" />
    <file src="bin\Release\Seq.Apps.dll" target="lib\net45" />
    <file src="bin\Release\Serilog.Sinks.File.dll" target="lib\net45" />
    <file src="bin\Release\Serilog.Sinks.RollingFile.dll" target="lib\net45" />
```
And now I get
```
System.InvalidCastException: Unable to cast object of type 'Seq.App.FileArchive.ArchiveWriterReactor' to type 'Seq.Apps.Reactor'.
   at Seq.Server.Features.Runner.AppHost.<>c.<.ctor>b__10_0(Type mrt)
   at Seq.Server.Features.Runner.AppHost..ctor(ILogger logger, Func`2 createReactorInstance, HostedApp hostedApp, AppInstance appInstance, AppHostSettings settings)
   at Seq.Server.Features.Runner.AppHost..ctor(IInternalEventPublisher publisher, HostedApp hostedApp, AppInstance appInstance, AppHostSettings settings)
   at Seq.Server.Features.Runner.SandboxedAppContainer.Initialize(IInternalEventPublisher publisher, String hostedApp, String appInstance, AppHostSettings settings)
   at Seq.Server.Features.Runner.SandboxedAppContainer.Initialize(IInternalEventPublisher publisher, String hostedApp, String appInstance, AppHostSettings settings)
   at Seq.Server.Features.Runner.RunningApp.LoadSandboxedAppContainer(AppDomain domain, HostedApp app)
   at Seq.Server.Features.Runner.RunningApp.Run()
```
Which I'm not sure how to solve.

Thanks
Steve

**Comment by nblumhardt** [comment]
Hi Steve, thanks for all the info.

You shouldn't need to include Seq.Apps.dll, Serilog.dll or either of the file sinks in the package, but you may need to make sure the versions line up with what Seq is currently using.

I.e. your packages.config file should be like:

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Seq.Apps" version="1.6.4" targetFramework="net45" />
  <package id="Serilog" version="2.0.0" targetFramework="net45" />
  <package id="Serilog.Sinks.File" version="2.0.0" targetFramework="net45" />
  <package id="Serilog.Sinks.RollingFile" version="2.1.0" targetFramework="net45" />
</packages>
```

One possible cause for the `MissingMethodException`, if these are already the versions you're referencing, could be out-of-date reference paths in your .csproj file. If you've upgraded Serilog for instance, the csproj may still be pointing at the old Serilog.dll. Any clues there?

Regards,
Nick

**Comment by stevescc** [comment]
Hi Nick,
I tried your suggested but unfortunately no dice. I haven't had any breakthrough with this so I thought I'd try the Seq.App.FileArchive nuget package. Installed it, created an instance, set the directory to an empty folder, then went back to the events page and selected 'Send to App' -> the instance, on a few events. The result after a few minutes is nothing. The ProgramData logs indicate that I've installed the app but that's it. No exception. And no files in the folder. It's not a restricted folder. If no one else is experiencing this issue it's made me think it's my install of Seq. So I uninstalled it then installed it again. Still nothing.
Do you have any other ideas I could try?
Thanks
Steve

**Comment by nblumhardt** [comment]
Hi Steve, thanks for the follow-up.

Just to be sure, I went through the same steps again here - fresh 3.3.23 install, installed the File Archive (latest) from NuGet, and sent some events manually - all working as expected. No clues there.

One thing I did realize is that the file archive app will suppress things like permissions errors (since it's based on the Serilog rolling file sink). Apart from permission to the folder, which it sounds like you've investigated,

 * is the file path a _filename_, not a folder name?
 * is the `{Date}` token in the filename, not another path segment?

Redirecting Serilog's [SelfLog](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics) to another location might reveal something - worth checking out.

I can jump onto a Skype call with you and help debug this if you're still blocked this week - feel free to drop me a line through nblumhardt/getseq.net if you'd like to set one up.

Cheers,
Nick

**Comment by stevescc** [comment]
Thanks for your assistance Nick. It was my mistake when testing the FileArchive app (I didn't specify the filename). And I just dug up an older Seq.App I made and it still works, so there must be something in my current project that's causing the InvalidCastException. Not sure exactly what yet but it's on my side I won't trouble you further here. Cheers, Steve

**Comment by nblumhardt** [comment]
Thanks for closing the loop, Steve. If there's any way I can help out further please just drop me a line 👍
