### ISSUE TITLE
Seq.App.Replication not working on latest docker image

### ISSUE THREAD

**Issue by patros** [datalust/seq-apps#57]
I can't get replication to work from one docker instance to another. Replication from our Windows VM based Seq works fine to both docker instances.

Under apps I can see a count for "events received by the app" but nothing is reaching the other docker instance.

There are no events reported as being emitted by the app. Let me know if there's any other logs/information I can provide.

**Comment by nblumhardt** [comment]
Thanks for the report; I've replicated this locally, I'll see what I can figure out 👍

**Comment by nblumhardt** [comment]
Hi @patros - in my case, the problem turned out to be network-related; once I configured the app to replicate to Seq at a different hostname (on another machine) all worked as expected. Guessing my attempts at finding the host from within the Docker container were incorrect.

Any chance this could be the problem with your setup?

Cheers,
Nick

**Comment by patros** [comment]
It's probably something like that. I've been off sick so haven't had a chance to confirm it.
