### ISSUE TITLE
Use default credentials

### ISSUE THREAD

**Issue by Ref83** [datalust/seq-apps#60]
I'd like to see a UseDefaultCredentials setting added to Seq.App.EmailPlus and Seq.App.Replication. 
This setting activates default credentials on sending email or replicate messages.
Can you add this feature? Or add me as a contributor of this repository and I will send you a pull request.

**Comment by nblumhardt** [comment]
Hi Alex, thanks for the note.

Using this for SMTP mail sounds straightforward - PR would be welcome (no particular contributor rights are required in order to send a PR). The changes would need to be tested locally with an existing app instance to ensure they're backwards-compatible with existing settings - i.e. the new setting would need to be `IsOptional = true`.

For replication, woudn't authenticating to the target Seq server using API keys be a more direct approach?
