### ISSUE TITLE
New Signal not showing in the Signal list

### ISSUE THREAD

**Issue by mjnorman** [datalust/seq-apps#61]
I am using SEQ 5.02375, and latest version of EmailPlus.  I created a new signal to capture events in the stream, and when I configure EmailPlus, it does not show this new signal.  

![image](https://user-images.githubusercontent.com/21270587/55513897-6dab3f80-562c-11e9-9a97-5afaa4d1a11d.png)

![image](https://user-images.githubusercontent.com/21270587/55514000-a0553800-562c-11e9-8edc-70a0f8d67b02.png)

**Comment by nblumhardt** [comment]
Hi @mjnorman - thanks for the note.

We've actually just made some tweaks in 5.1 to improve the UX around this :-) ... the problem is that apps  can only receive input from _shared_ signals.

If you edit the _XMLPort Errors_ signal and from the drop-down choose _Shared_, then save, it should show up in the list.

HTH!
