### ISSUE TITLE
File Archiver

### ISSUE THREAD

**Issue by mick1313** [datalust/seq-apps#68]
We have our SEQ deployed in an container, can we set the file path to a cloud location for long term storage, or does the location need to be relative to the container? For instance, can in save to blob storage in azure?

**Comment by nblumhardt** [comment]
Hi @mick1313 ,

The file archive app only writes logs to a local path (or mapped network location), but is intended to be used in conjunction with file sync to some external location.

For Azure Blob Storage, a scheduled `azcopy` task might be used to do this hourly; I think there are other tools out there to watch and upload files from a folder on the fly.

In case you haven't spotted it, _Seq.App.JsonArchive_ is often a better bet for archival storage, since it preserves all structured data and produces files that can be read back into Seq.

Hope this helps!

**Comment by mick1313** [comment]
I wasn't sure which one to use.  the azcopy task is probably what we need.  We are using the image container directly from SEQ.  No changes.   Are there any samples anywhere that use the JSON archive to create a file in the container storage?  I am not sure what their file system looks like.  Also, what options does the JSON Archive have, documentation is limited?

**Comment by nblumhardt** [comment]
Thanks for your reply.

The JSON archive app has very similar options to the file archive, namely a path/filename template, and maximum chunk size.

Under Docker, you can mount a folder on the host to any path within the container. So for example, if your host's local folder path is `/home/user/events` you can map this to e.g. `/archive` in the container with: `-v /home/user/events:/archive`.

Then, in Seq you can specific an archive location under `/archive` and write the JSON file set there.
